version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:16.20.0 # Use the correct Node.js image

jobs:
  install-dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install --legacy-peer-deps

  build:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - nextjs-dependencies-{{ checksum "package-lock.json" }}
            - nextjs-dependencies-
      - run:
          name: Install Dependencies
          command: npm install --legacy-peer-deps
      - save_cache:
          key: nextjs-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build Application
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .next

  test:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - nextjs-dependencies-{{ checksum "package-lock.json" }}
            - nextjs-dependencies-
      - run:
          name: Run Tests
          command: npm test

  deploy:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Deploy to Production
          command: npm run deploy # Customize this for your deployment (e.g., Vercel, AWS, Netlify)

workflows:
  version: 2
  nextjs-workflow:
    jobs:
      - install-dependencies
      - build:
          requires:
            - install-dependencies
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
