version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Interact with Website
          command: |
            curl -X POST https://example.com/api -d '{"key": "value"}' \
              -H "Content-Type: application/json"